### PR TITLE
[skip ci] fix images

### PR DESCRIPTION
**Pull request by X1nto**
Also replaced `new MethodHook()` with `new PinePatchFn(callFrame -> {})`

### CODE REVIEW

**Comment by Vendicated** [comment]
<3

**Comment by Vendicated** [comment]
Wrong button

**Comment by Vendicated** [comment]
tfw fix settings.gradle

**Comment by X1nto** [comment]
> tfw fix settings.gradle

Haha, always forgetting to change back settings.gradle

**Pull request merged**
